---
- name: Install basic packages
  become: true
  dnf:
      name: "{{ item }}"
      state: present
  with_items:
      - htop
      - ftop
      - powertop
      - git
      - tmux
      - neovim
      - mozilla-fira-mono-fonts
      - mozilla-https-everywhere
      - gobby05
      - httpie
      - vagrant
      - vagrant-sshfs
      - rpmdevtools
      - redhat-rpm-config
      - hexchat
      - pipenv
      - inkscape
      - ripgrep
      - podman
      - buildah

- name: Remove not used packages
  become: true
  dnf:
      name: "{{ item }}"
      state: absent
  with_items:
      - cheese
      - evolution
      - evolution-ews
      - evolution-help
      - gnome-boxes
      - gnome-calendar
      - gnome-contacts
      - gnome-dictionary
      - gnome-getting-started-docs
      - gnome-initial-setup
      - gnome-maps
      - gnome-online-miners
      - gnome-user-docs
      - gnome-user-share
      - gnome-weather
      - tracker-miners
      - yelp
      - rhythmbox

- name: ensure core gnome packages are installed
  become: true
  dnf:
    name:
      - eog
      - evince
      - evolution-data-server
      - flatpak
      - gdm
      - gnome-keyring
      - gnome-menus
      - gnome-screenshot
      - gnome-shell
      - gnome-terminal
      - gnome-tweaks
      - nautilus
      - redhat-menus
    state: present

- name: Add user to wheel group
  user:
      name: "{{ username }}"
      groups: wheel
      append: yes

- name: Install .bashrc
  file:
        src: "{{ files }}/bashrc"
        dest: "{{ ansible_user_dir }}/.bashrc"
        mode: 0644
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        force: yes
        state: link

- name: Install .tmux.conf
  file:
        src: "{{ files }}/tmux.conf"
        dest: "{{ ansible_user_dir }}/.tmux.conf"
        mode: 0644
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        force: yes
        state: link

- name: Install .gitconfig
  file:
        src: "{{ files }}/gitconfig"
        dest: "{{ ansible_user_dir }}/.gitconfig"
        mode: 0644
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        force: yes
        state: link

- name: Copy neovim configuration
  synchronize:
      src: nvim/
      dest: "{{ ansible_user_dir }}/.config/nvim"

