---
- name: Install basic packages
  become: true
  dnf:
      name: "{{ item }}"
      state: present
  with_items:
      - vim
      - powerline
      - mozilla-fira-mono-fonts
      - vim-powerline
      - git
      - python3-flake8
